#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse

__author__ = "Piotr Gawlowicz"
__copyright__ = "Copyright (c) 2017, Technische Universität Berlin"
__version__ = "0.1.0"
__email__ = "gawlowicz@tkn.tu-berlin.de"


import remote_agent_managers


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--port',
                        type=int,
                        default=567890,
                        help='Port on which Agent host listens for cmds.')

    args = parser.parse_args()
    port = args.port

    remoteAgentHost = remote_agent_managers.RemoteAgentHost(port)
    remoteAgentHost.start_cmd_rx()
